spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: xiaoyu
      password: 123456
      type: org.apache.commons.dbcp2.BasicDataSource
      dbcp2:
            default-auto-commit: true
            initial-size: 30
            max-total: 120
            max-idle: 120
            min-idle: 30
            max-wait-millis: 10000
            validation-query: 'SELECT 1'
            validation-query-timeout: 3
            test-on-borrow: true
            test-while-idle: true
            time-between-eviction-runs-millis: 10000
            num-tests-per-eviction-run: 10
            min-evictable-idle-time-millis: 120000
            remove-abandoned-on-borrow: true
            remove-abandoned-timeout: 120
            pool-prepared-statements: true
  redis:
      database: 1
      host: 47.98.108.55
      password: 123456
  jpa:
      open-in-view: true
      hibernate:
        ddl-auto: update
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          my-client-1:
            client-id: client_1
            client-secret: 123456
            client-scop: select
            authorization-grant-type: client_credentials
            client-authentication-method: basic
            #provider: my-oauth-provider
          my-client-2:
            client-id: client_2
            client-secret: 123456
            client-scop: select
            authorization-grant-type: password
        provider:
          my-oauth-provider:
            authorization-url: /oauth/authorize
            token-uri: /oauth/token
            user-info-uri: /userinfo
            jwk-set-uri: /token_keys
            user-name-attribute: order
    filter:
      order: 3
server:
  port: 8080

